name: next_app
description: FPT Retail mobile app

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_svg: ^2.0.5

  flutter_native_splash: ^2.2.19

  shared_preferences: ^2.2.2

  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

#   flutter_launcher_icons: ^0.13.1

# flutter_launcher_icons:
#   android: true
#   image_path: "assets/images/ic_launcher.png"
#   adaptive_icon_background: "#FFFFFF"
#   ios: true
#   image_path_ios: "assets/images/ic_launcher_ios.png"
#   remove_alpha_ios: true

flutter_native_splash:
  image: assets/images/splash.png
  background_image: assets/images/splash_background.png

  # windowDrawsSystemBarBackgrounds: true (change manually in styles.xml
  # every time run 'pub run flutter_native_splash:create')

  android_12:
    color: "#F5F5F5"
    image: assets/images/android_12_splash.png

    # color_dark: "#000000"
    # image_dark: assets/images/android_12_splash_dark.png

  android: true
  ios: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/vectors/
